import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Fragment } from "react";
import { AddToWeeklyMenu } from "../../../components/weekly-menu/AddToWeeklyMenu";
import { getRecipe, recipes } from "../../../lib/recipes";
import { formatScaledQuantity, getIngredientScalingRule, scaleIngredientQuantity } from "../../../lib/weekly-menu";

export function generateStaticParams() { return recipes.map((recipe) => ({ slug: recipe.slug })); }
export default async function RecipePage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ portioner?: string }> }) {
  const { slug } = await params; const recipe = getRecipe(slug); if (!recipe) notFound();
  const query = await searchParams; const requested = Number(query.portioner); const selectedServings = Number.isFinite(requested) ? Math.max(1, Math.min(24, Math.round(requested))) : recipe.servings;
  return <main className="recipe-detail"><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">S</span><span>Smakfamiljen</span></Link><div className="detail-header-links"><Link href="/veckomeny">Veckomeny</Link><Link href="/" className="back-link">← Till alla recept</Link></div></header><div className="detail-shell"><div className="detail-image"><Image src={recipe.image} alt={recipe.title} fill priority sizes="(max-width: 850px) 100vw, 52vw" /></div><article className="detail-copy"><p className="kicker">{recipe.category} · {recipe.health}</p><h1>{recipe.title}</h1><p className="detail-intro">{recipe.description}</p><div className="detail-meta"><span><strong>{recipe.timeMinutes}</strong> minuter</span><span><strong>{selectedServings}</strong> portioner</span><span><strong>{recipe.difficulty}</strong> svårighet</span></div>{selectedServings !== recipe.servings ? <p className="scaled-note">Mängderna är anpassade från {recipe.servings} till {selectedServings} portioner.</p> : null}<AddToWeeklyMenu recipeSlug={recipe.slug} recipeTitle={recipe.title} servings={selectedServings} /><div className="detail-columns"><div><h2>Ingredienser</h2><ul className="ingredients">{recipe.ingredients.map((item, index) => <Fragment key={`${item.group ?? "ingredient"}-${item.name}-${index}`}>{item.group && item.group !== recipe.ingredients[index - 1]?.group ? <li className="ingredient-group">{item.group}</li> : null}<li><span>{item.name}</span><strong>{item.amount === null ? item.unit : `${formatScaledQuantity(scaleIngredientQuantity(item.amount, recipe.servings, selectedServings, getIngredientScalingRule(item)))} ${item.unit}`}</strong></li></Fragment>)}</ul></div><div><h2>Gör så här</h2><ol className="steps">{recipe.steps.map((step, index) => <li key={step}><span>{index + 1}</span><p>{step}</p></li>)}</ol></div></div>{recipe.healthReason ? <aside className="health-note"><span>✦</span><div><h2>Varför passar rätten i vardagen?</h2><p>{recipe.healthReason}</p></div></aside> : null}</article></div></main>;
}
